remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: pets predictor html file
description: Some basic examples of client interfaces to a computer vision API

author:
  name: Chau Tran
